version: '3'

services:
  postgres:
    image: postgres:10
    environment:
      POSTGRES_USER: "felipe"
      POSTGRES_PASSWORD: "felipe123"
      POSTGRES_DB: "data_facecpar"
    ports:
      - "5432:5432"
    networks:
      - pg-network
 
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "felipe@data_facecpar.inc"
      PGADMIN_DEFAULT_PASSWORD: "felipe123"
    ports:
      - "8080:80" # Esquerda Externo:Direita Interno
    depends_on:
      - postgres
    networks:
      - pg-network

networks:
  pg-network:
    driver: bridge    
    